hl.on("hyprland.start", function()
	hl.exec_cmd("slack", { workspace = 10 })
	hl.exec_cmd(cfg.browser, { workspace = 1 })
	hl.exec_cmd(cfg.terminal, { workspace = 2 })
	hl.exec_cmd("waybar")
	hl.exec_cmd("indicator-sound-switcher")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("flameshot")
end)
