background-color=#1b121c
text-color=#fafafa
markup=1

[urgency=low]
border-color=#fafafa
format=<span foreground="#fafafa">•</span> <b>%s</b>\n%b

[urgency=normal]
border-color=#7aa2f7
format=<span foreground="#7aa2f7">●</span> <b>%s</b>\n%b

[urgency=high]
border-color=#ff1111
format=<span foreground="#ff1111">⚠</span> <b>%s</b>\n%b
default-timeout=0
