is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\S+/)?g?(view|n?vim?x?|fzf)(diff)?$'"

# Global navigation (disabled inside SSH)
bind -n C-h if-shell '[ -z "$SSH_CONNECTION" ] && '"$is_vim"'' "send-keys C-h" "if-shell '[ -z \"$SSH_CONNECTION\" ]' 'select-pane -L'"
bind -n C-j if-shell '[ -z "$SSH_CONNECTION" ] && '"$is_vim"'' "send-keys C-j" "if-shell '[ -z \"$SSH_CONNECTION\" ]' 'select-pane -D'"
bind -n C-k if-shell '[ -z "$SSH_CONNECTION" ] && '"$is_vim"'' "send-keys C-k" "if-shell '[ -z \"$SSH_CONNECTION\" ]' 'select-pane -U'"
bind -n C-l if-shell '[ -z "$SSH_CONNECTION" ] && '"$is_vim"'' "send-keys C-l" "if-shell '[ -z \"$SSH_CONNECTION\" ]' 'select-pane -R'"

# Prefix + navigation (always works)
bind C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
