unbind C-a
set -g prefix C-g
bind-key C-g send-prefix

set -g mouse on

unbind -n MouseDrag1Pane
unbind -n MouseDrag1Border
unbind -n MouseDrag1Status

bind -n MouseDrag1Pane send-keys -M
bind -n MouseDrag1Border send-keys -M
bind -n MouseDrag1Status send-keys -M
